// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_dist
NumericMatrix cpp_dist(NumericMatrix m1, NumericMatrix m2);
RcppExport SEXP _MagmaClustR_cpp_dist(SEXP m1SEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dist(m1, m2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_perio
NumericMatrix cpp_perio(NumericMatrix m1, NumericMatrix m2, double period);
RcppExport SEXP _MagmaClustR_cpp_perio(SEXP m1SEXP, SEXP m2SEXP, SEXP periodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< double >::type period(periodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_perio(m1, m2, period));
    return rcpp_result_gen;
END_RCPP
}
// cpp_perio_deriv
NumericMatrix cpp_perio_deriv(NumericMatrix m1, NumericMatrix m2, double period);
RcppExport SEXP _MagmaClustR_cpp_perio_deriv(SEXP m1SEXP, SEXP m2SEXP, SEXP periodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< double >::type period(periodSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_perio_deriv(m1, m2, period));
    return rcpp_result_gen;
END_RCPP
}
// cpp_prod
NumericMatrix cpp_prod(NumericMatrix m1, NumericMatrix m2);
RcppExport SEXP _MagmaClustR_cpp_prod(SEXP m1SEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_prod(m1, m2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_noise
NumericMatrix cpp_noise(NumericMatrix m1, NumericMatrix m2, double noise);
RcppExport SEXP _MagmaClustR_cpp_noise(SEXP m1SEXP, SEXP m2SEXP, SEXP noiseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< double >::type noise(noiseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_noise(m1, m2, noise));
    return rcpp_result_gen;
END_RCPP
}
