# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dist <- function(m1, m2) {
    .Call(`_MagmaClustR_cpp_dist`, m1, m2)
}

cpp_perio <- function(m1, m2, period) {
    .Call(`_MagmaClustR_cpp_perio`, m1, m2, period)
}

cpp_perio_deriv <- function(m1, m2, period) {
    .Call(`_MagmaClustR_cpp_perio_deriv`, m1, m2, period)
}

cpp_prod <- function(m1, m2) {
    .Call(`_MagmaClustR_cpp_prod`, m1, m2)
}

cpp_noise <- function(m1, m2, noise) {
    .Call(`_MagmaClustR_cpp_noise`, m1, m2, noise)
}

